### ISSUE TITLE
about clang

### ISSUE THREAD

**Issue by liusiyu58** [dslab-epfl/asap#1]
seems git clone http://llvm.org/git/clang.git asap/tools/clang does not work now?

**Comment by Sjlver** [comment]
It looks like the LLVM repository has moved. Try
https://github.com/llvm/llvm-project

I haven't compiled ASAP in a while. If it works for you, please do send me
a pull request so that I can update the instructions. If you get stuck and
have more questions, let me know and I'll try to help.

**Comment by liusy58** [comment]
thx a lot sir, but I encountered another question : 

when I try ASAP on a small example, the error message shows 

```
asap-clang -asap-init >/dev/null
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- parallel (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:24:in `<main>'
```

**Comment by Sjlver** [comment]
Ah... that's because asap-clang is a wrapper script for clang written in
Ruby, and it requires a few libraries. Sorry about that -- I'll try to
document it better. Please let me know what you did so far, that would be
very helpful for updating the docs.

First, you'll need ruby and rubygems. If you're on Linux, something like
`sudo apt install ruby rubygems` should do the trick. You can also use
https://rvm.io/ if you have other projects that depend on specific versions
of Ruby.

After that, you'll need to install the libraries. This command should work:
`gem install parallel`. I don't think ASAP uses other libraries, but if you
get similar error messages, try `gem install
name-of-the-file-that-can-t-be-loaded`.

Hope this works! It's been five years since I've worked with ASAP so my
memory is a little rusty, but I'm happy to help more if needed.

**Comment by Sjlver** [comment]
I've just read the error message that you've got in more detail, and see
that ruby and rubygems are already installed. So probably the only command
that you need to run is `gem install parallel`. Or maybe `sudo gem install
parallel` if it doesn't work otherwise.

Hope this helps!

**Comment by liusy58** [comment]
I solved the problem above but still some questions remaining:

```
asap-clang -asap-init >/dev/null
mkdir -p stamps
touch stamps/sum-asap-init
asap-clang -Wall -g -O1 -fsanitize=address   -c -o sum.o sum.c
sum.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
sum.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
/Users/liusiyu/Downloads/asap/lib/Transforms/SanityChecks/asap-clang-utils.rb:20:in `run!': Command /Users/liusiyu/Downloads/asap/build/bin/clang failed with status pid 63014 exit 1 (RunExternalCommandError)
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:159:in `do_compile'
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:238:in `do_compile'
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:131:in `exec'
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:484:in `main'
        from /Users/liusiyu/Downloads/asap/build/bin/asap-clang:526:in `<main>'
make: *** [sum.o] Error 1
```

It seems that the header file cannot be included.

Much thanks for your generous help!

**Comment by Sjlver** [comment]
It looks like the standard C header files are not installed on your machine.

This StackOverflow question has more information about the problem:
https://stackoverflow.com/questions/26333823/clang-doesnt-see-basic-headers
I'm not sure what the solution is, but my first try would be to install the
XCode command line tools (I'm assuming from your error message that you're
on Mac OS). The command for this is xcode-select --install. More
information here:
https://stackoverflow.com/questions/9329243/how-to-install-xcode-command-line-tools

Hope this helps!

**Comment by liusy58** [comment]
Thx a lot! I'll have a try~ And I'll make a pull request later for your updating ~

**Comment by Sjlver** [comment]
If that does not help, you can check where clang looks for the header
files, by adding the "-v" flag to asap-clang:

asap-clang -v -Wall -g -O1 -fsanitize=address   -c -o sum.o sum.c

You can also try setting the C_INCLUDE_PATH and CPLUS_INCLUDE_PATH
environment variables.

**Comment by liusy58** [comment]
Thx for your patient explanation~

**Comment by Sjlver** [comment]
Did you get it working? I'm curious ;-)

**Comment by liusy58** [comment]
yeah, it works fine on ubuntu, but a pity that the library problem cannot be fixed on macOS now~
